=== neilmanoj/HTML-PROGRAMS/lab3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="hotelmanagement">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="hotel" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="hid">
                <xs:simpleType>
                  <xs:restriction base="xs:integer">
                    <xs:pattern value="[0-9]"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="name">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="([a-zA-Z])*"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element name="address" type="xs:string" />
              <xs:element  name="customerid">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:pattern value="([a-zA-Z0-9])*"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:element>
              <xs:element type="xs:string" name="managerid"/>
              <xs:element type="xs:integer" name="inputid"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== neilmanoj/HTML-PROGRAMS/lab3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="lab3.xsl" type="text/xsl"?>
<hotelmanagement xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="lab3.xsd">
	<hotel>
		<hid>1</hid>
		<name>Taj hotels</name>
		<address>kochi</address>
		<customerid>null</customerid>
		<managerid>null</managerid>
		<inputid>1</inputid>
	</hotel>
	<hotel>
		<hid>1</hid>
		<name>Taj hotels</name>
		<address>Trivandrum</address>
		<customerid>1</customerid>
		<managerid>null</managerid>
		<inputid>2</inputid>
	</hotel>
	<hotel>
		<hid>1</hid>
		<name>Taj hotels</name>
		<address>chennai</address>
		<customerid>1</customerid>
		<managerid>1</managerid>
		<inputid>3</inputid>
	</hotel>
	<hotel>
		<hid>1</hid>
		<name>Taj hotels</name>
		<address>banglore</address>
		<customerid>2</customerid>
		<managerid>null</managerid>
		<inputid>3</inputid>
	</hotel>
	<hotel>
		<hid>1</hid>
		<name>Taj hotels</name>
		<address>Mumbai</address>
		<customerid>2</customerid>
		<managerid>1</managerid>
		<inputid>4</inputid>
	</hotel>
</hotelmanagement>
